### ISSUE TITLE
Update to Kirkstone

### ISSUE THREAD

**Issue by offa** [jhnc-oss/yocto-build#50]
Update the default to *kirkstone*.

~~Should we build Dunfell and Kirkstone in CI?~~ --> dedicated `dunfell` branch

- [x] Merge *kirkstone* to *main* — #53 
- [x] Sync *main* to *kirkstone* — #55 
- [x] Document supported versions — #54
